// <auto-generated />
using System;
using JanTaskTracker.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JanTaskTrackerAPI.Migrations
{
    [DbContext(typeof(JanTaskTrackerDbContext))]
    partial class JanTaskTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JanTaskTracker.Server.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "Finance"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "Human Resources"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Information Technology"
                        });
                });

            modelBuilder.Entity("JanTaskTracker.Server.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            DepartmentId = 1,
                            Name = "Bob Smith",
                            RoleId = 2,
                            Salary = 70000m
                        },
                        new
                        {
                            EmployeeId = 2,
                            DepartmentId = 2,
                            Name = "Catherine Green",
                            RoleId = 5,
                            Salary = 65000m
                        },
                        new
                        {
                            EmployeeId = 3,
                            DepartmentId = 3,
                            Name = "David Brown",
                            RoleId = 7,
                            Salary = 90000m
                        });
                });

            modelBuilder.Entity("JanTaskTracker.Server.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            Description = "First project",
                            ProjectName = "Project Alpha",
                            Status = "Active"
                        },
                        new
                        {
                            ProjectId = 2,
                            Description = "Second project",
                            DueDate = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectName = "Project Beta",
                            StartDate = new DateTime(2024, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("JanTaskTracker.Server.Models.ProjectTask", b =>
                {
                    b.Property<int>("ProjectTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectTaskId"));

                    b.Property<string>("AssignedEmployeeIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProjectTaskId");

                    b.ToTable("ProjectTasks");

                    b.HasData(
                        new
                        {
                            ProjectTaskId = 1,
                            AssignedEmployeeIds = "[1,3]",
                            Description = "Task for Project Alpha",
                            DueDate = new DateTime(2024, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = 1,
                            StartDate = new DateTime(2024, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            Title = "Task 1"
                        },
                        new
                        {
                            ProjectTaskId = 2,
                            AssignedEmployeeIds = "[2,3]",
                            Description = "Another Task for Project Alpha",
                            DueDate = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = 1,
                            StartDate = new DateTime(2024, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            Title = "Task 2"
                        },
                        new
                        {
                            ProjectTaskId = 3,
                            AssignedEmployeeIds = "[1,2]",
                            Description = "Task for Project Beta",
                            DueDate = new DateTime(2025, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = 2,
                            StartDate = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            Title = "Task 3"
                        },
                        new
                        {
                            ProjectTaskId = 4,
                            AssignedEmployeeIds = "[1,2]",
                            Description = "Another Task for Project Beta",
                            DueDate = new DateTime(2025, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProjectId = 2,
                            StartDate = new DateTime(2024, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active",
                            Title = "Task 4"
                        });
                });

            modelBuilder.Entity("JanTaskTracker.Server.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            DepartmentId = 1,
                            RoleName = "Accountant"
                        },
                        new
                        {
                            RoleId = 2,
                            DepartmentId = 1,
                            RoleName = "Financial Analyst"
                        },
                        new
                        {
                            RoleId = 3,
                            DepartmentId = 1,
                            RoleName = "Finance Manager"
                        },
                        new
                        {
                            RoleId = 4,
                            DepartmentId = 2,
                            RoleName = "HR Assistant"
                        },
                        new
                        {
                            RoleId = 5,
                            DepartmentId = 2,
                            RoleName = "HR Specialist"
                        },
                        new
                        {
                            RoleId = 6,
                            DepartmentId = 2,
                            RoleName = "HR Director"
                        },
                        new
                        {
                            RoleId = 7,
                            DepartmentId = 3,
                            RoleName = "Software Engineer"
                        },
                        new
                        {
                            RoleId = 8,
                            DepartmentId = 3,
                            RoleName = "Front-End Developer"
                        },
                        new
                        {
                            RoleId = 9,
                            DepartmentId = 3,
                            RoleName = "Back-End Developer"
                        },
                        new
                        {
                            RoleId = 10,
                            DepartmentId = 3,
                            RoleName = "Full-Stack Developer"
                        });
                });

            modelBuilder.Entity("JanTaskTracker.Server.Models.Employee", b =>
                {
                    b.HasOne("JanTaskTracker.Server.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JanTaskTracker.Server.Models.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("JanTaskTracker.Server.Models.Role", b =>
                {
                    b.HasOne("JanTaskTracker.Server.Models.Department", "Department")
                        .WithMany("Roles")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("JanTaskTracker.Server.Models.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("JanTaskTracker.Server.Models.Role", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
